general {
	hide_cursor = true
}

background {
	monitor =
	path = /home/kiyuen/wallpaper/flower.jpg
}

input-field {
	monitor =
	size = 200, 25
	outline_thickness = 2
	dots_size = 0.2	
	font_family = JetBrains Mono NL
	inner_color = rgba(0,0,0,0.5)
	font_color = rgba(255,255,255,0.5)
	position = 0, -200
}

label {
	monitor = 
	text = cmd[update:1000] echo "$TIME"
	color = rgba(255,255,255,1.0)
	font_size = 33
	font_family = JetBrains Mono NL
	halign = center
	valign = center
	position = 200, 0
}

label {
	monitor =
	text = $USER
	color = rgba(255,255,255,1.0)
	font_size = 33
	font_family = JetBrains Mono NL
	halign = center
	valign = center
	position = -200, 0
}
